enum GENDER {
  FEMALE = 'FEMALE',
  MALE = 'MALE',
  OTHER = 'OTHER',
}

enum SOCIAL_MEDIA {
  FACEBOOK = 'FACEBOOK',
  TWITTER = 'TWITTER',
  INSTAGRAM = 'INSTAGRAM',
  TIK_TOK = 'TIK_TOK',
  SNAPCHAT = 'SNAPCHAT',
}

export { GENDER, SOCIAL_MEDIA }
