enum GENDER {
  FEMALE = 'FEMALE',
  MALE = 'MALE',
  OTHER = 'OTHER',
}
enum VIEW_TYPE {
  LIST = 'LIST',
  CARD = 'CARD'
}

enum VIEW_DENSITY {
  COMPACT = 'COMPACT',
  DEFAULT = 'DEFAULT'
}

enum VIEW_ALIGN {
  END = 'END',
  CENTER = 'CENTER',
  START = 'START'
}

enum ROLE {
  USER = 'USER',
  ADMIN = 'ADMIN'
}

enum EXCEL_FIELD_TYPE {
  VALUE = 'VALUE',
  SUM = 'SUM',
  GREATER = 'GREATER',
  LOWER = 'LOWER',
}

export { GENDER, VIEW_TYPE, ROLE, VIEW_DENSITY, VIEW_ALIGN, EXCEL_FIELD_TYPE }
