export declare enum GENDER {
  WOMAN = 'WOMAN',
  MAN = 'MAN',
  TRANSGENDER = 'TRANSGENDER',
  GENDER_NEUTRAL = 'GENDER_NEUTRAL',
  NON_BINARY = 'NON_BINARY',
  INTERSEX = 'INTERSEX',
  GENDERQUEER = 'GENDERQUEER',
  THIRD_GENDER = 'THIRD_GENDER',
  TRANS = 'TRANS',
  NON_BINARY = 'NON_BINARY',
  AGENDER = 'AGENDER',
  OTHER = 'OTHER',
}
